name: "Format Check"

on:
  push:
    branches:
      - 'main'
      - 'release-'
    tags: '*'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  runic:
    name: "Runic Format Check"
    uses: "SciML/.github/.github/workflows/runic.yml@v1"
    secrets: "inherit"
